### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Bexpg-0** [rubbyl33t/pollery#3]
When im build stealer (not in vs) im getting (web.client http reuqest error 522) i think its happen because of save decrypter can you release save decrypter source ama decrypter not working

**Comment by pastebtw** [comment]
what a goober, kys

**Comment by N-a-h** [comment]
delete cryptography regkey, it's a known windows bug

**Comment by Bexpg-0** [comment]
> delete cryptography regkey, it's a known windows bug

Which line

**Comment by Bexpg-0** [comment]
@N-a-h
