### ISSUE TITLE
Will you open your website back

### ISSUE THREAD

**Issue by Bexpg-0** [rubbyl33t/pollery#4]
???

**Comment by pastebtw** [comment]
what a dumb shit

**Comment by Bexpg-0** [comment]
Codebase.txt missing without codebase.txt cant buils

**Comment by pastebtw** [comment]
do me a favour and shut the fuck up

**Comment by rubbyl33t** [comment]
do me a favour and shut the fuck up and stop using the issues tab as chat rooms
