### ISSUE TITLE
Can`t build

### ISSUE THREAD

**Issue by bexpg000** [rubbyl33t/pollery#6]
can`t build because of codebase.txt 1!??????!!!!!!!!!

**Comment by gtmarket** [comment]
nooooob

**Comment by bexpg000** [comment]
> nooooob

u pro?!!?@@@

**Comment by gtmarket** [comment]
why r u rertarted

-crandetan

**Comment by rubbyl33t** [comment]
its krandetän not crandetan

**Comment by bexpg000** [comment]
its was memes  lmao. i already know how to build

**Comment by bexpg000** [comment]
i used stub files to build

**Comment by bexpg000** [comment]
rubby  didnt add savedecrypter but i found in internet

**Comment by bexpg000** [comment]
@rubbyl33t  what ur discord ?
